Algoritmo "semnome"

Var
   numero, x, soma, contador: inteiro


Inicio
   escreva ("Informe um número: ")
   leia (numero)
   enquanto (numero < 0) ou (numero > 0) faca
      leia (numero)
      soma <- x + 1
      contador <- numero + numero
      escreva ("Informe um número: ")
      leia (numero)
   fimenquanto
   escreval ("Soma total: ", soma)
   escreval ("Contagem: ", contador)
Fimalgoritmo